### ISSUE TITLE
Is there size limit for a message?

### ISSUE THREAD

**Issue by myeongsikyoon** [NewLifeX/NewLife.RocketMQ#31]
I have some trouble to send large size of message. When i send large size message from Sender Program written in java, NewLife.RocketMQ client can receive it. but message body broken. (small size message is OK)
How long message size can be support? Is there size limit for a message?

Additional Test:
1. Combination Sender written in NewLife.RocketMQ and Listener written in NewLife.RocketMQ : SUCCESS
2. Combination Sender written in Java and Listener written in Java : SUCCESS
3. Combination Sender written in NewLife.RocketMQ and Listener written in Java : SUCCESS
4. Combination Sender written in Java and Listener written in NewLife.RocketMq : FAIL

**Comment by nnhy** [comment]
that is a bug!
It was fixed in 0509

https://github.com/NewLifeX/NewLife.RocketMQ/commit/2b37dd31fa39ca266b9e12d92c12050f9483d02e
https://github.com/NewLifeX/NewLife.RocketMQ/commit/5c4c9ab53dce6eb11a5f72ddb2b3a77d8578ca0b
https://github.com/NewLifeX/NewLife.RocketMQ/commit/c68d9ac68456c69fa6ec9aa4737a41b3e726b408
